server:
  servlet.context-path: /kedop/missing-person
  port: 8081

spring:
  jpa:
    hibernate:
      ddl-auto: none
    database: postgresql
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    name: kedop
    url: jdbc:postgresql://localhost:5432/kedop_missing_person
    username: postgres
    password: postgres
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: liquibase-changelog.xml
    default-schema: missing_person
  kafka:
    bootstrap-servers: kakfa:9092
    consumer:
      group-id: "kedop"
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

