package com.kedop.missingperson.exceptions;

/**
 * @author oleksandrpolishchuk on 31.01.2023
 * @project MissingPerson
 */
@SuppressWarnings(value = "unused")
public enum ExceptionCode {

    REPEATER_ERROR,
    JSON_SERIALIZATION_ERROR,
    JSON_DESERIALIZATION_ERROR,
    USER_ERROR,
    NOTIFICATION_ERROR,
    INSUFFICIENT_SCOPES,
    INSUFFICIENT_AUTHENTICATION,
    UNEXPECTED_OPERATION,
    CONSTRAINT_VIOLATION,
    JSON_PARSE_ERROR,
    RESOURCE_ACCESS_ERROR,
    REST_CLIENT_ERROR,
    MISSING_PARAMETER,
    CUSTOMER_ERROR,
    ADMIN_ERROR,
    UNEXPECTED_ERROR,
    DATA_ACCESS,
    PARAMETER_FORMAT_ERROR
}
